In [ ]:
# 1
# pentru pixelii din margine: facem padding (cu orice, in solutiq era -1, putem si 256)
# ideea e sa fie la fel
# obtinem vectorii cu 0 si 1
# pentru frecventa putem sa folosim un dictionar
# cu cheile valorile in baza 10 a vectorilor (sau stringuri cu vectorul)
# si valorile frecventa

In [ ]:
# 2
# in loc de sobel putem sa comparam 2 pixeli (pt margine facem padding)
# p0 p1
# p2 p3
# pentru a calcula gradientul pentru p0: 
# pe directia x facem p0 - p1
# pe directia y facem p0 - p2
# gen p0 e x si e e p1 sau p2 (cred?)

In [ ]:
# 3
# daca directie a 15 grade, comparam pixelul din stanga cu cel din dreapta
# daca directie e 90 de grade, comparam pixelul de sus cu cel de jos

In [ ]:
# 4
# folosim knn din scikit learn (nu implementam de mana)

In [ ]:
# 5
# clf = SVC(kernel='precomputed')

In [8]:
import numpy as np

x = np.arange(24).reshape(2, 3, 4)
print(x)
print()
print(np.sum(x, axis=0))
print()
print(np.sum(x, axis=1))
print()
print(np.sum(x, axis=2))
print()
print(np.sum(x, axis=(0, 1)))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

[[12 15 18 21]
 [48 51 54 57]]

[[ 6 22 38]
 [54 70 86]]

[60 66 72 78]


In [10]:
h = np.zeros((3, 3))
print(h)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
x = [[1, 2, 3, 4], [5, 6, 7, 8]]
x = np.array(x)
print(x)
x = x.reshape(-1, 2, 2)
print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(x)
print()
x = x.reshape(-1, 2, 2)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
